version: '3.7'

services:

  bitbucket:
    image: 'atlassian/bitbucket-server:latest'
    restart: unless-stopped
    container_name: bitbucket
    environment:
      JMX_ENABLED: 'false'
    ports:
      - '7990:7990'
      - '7999:7999'
    extra_hosts:
      - 'localdc:${HOST_IP:?err}'
    volumes:
      - ./.container/bitbucket:/var/atlassian/application-data/bitbucket
