version: '3.7'

services:

  gitlab_pg:
    image: postgres:9.6.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: gitlab
      POSTGRES_PASSWORD: gitlab
      POSTGRES_DB: gitlabhq_production
      PGDATA: /var/lib/postgresql/data
    ports:
      - '5432:5432'
    volumes:
      - ./.container/gitlab_pg_data:/var/lib/postgresql/data/
  
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: unless-stopped
    container_name: gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localdc:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
        monitoring_role['enable'] = false
        prometheus['enable'] = false
        prometheus['monitor_kubernetes'] = false
        grafana['enable'] = false
        gitlab_pages['enable'] = false
        gitlab_ci['gitlab_ci_all_broken_builds'] = true
        gitlab_ci['gitlab_ci_add_pusher'] = true
        redis['enable'] = true
        postgresql['enable'] = false
        gitlab_rails['db_adapter'] = "postgresql"
        gitlab_rails['db_encoding'] = "unicode"
        gitlab_rails['db_database'] = "gitlabhq_production"
        gitlab_rails['db_username'] = "gitlab"
        gitlab_rails['db_password'] = "gitlab"
        gitlab_rails['db_host'] = "gitlab_pg"
        gitlab_rails['db_port'] = 5432
        gitlab_rails['initial_root_password'] = "password"
    depends_on:
      #- gitlab_redis
      - gitlab_pg
    ports:
      - '8929:8929'
      - '2224:22'
    extra_hosts:
      - 'localdc:${HOST_IP:?err}'
    volumes:
      - ./.container/gitlab/config:/etc/gitlab
      - ./.container/gitlab/logs:/var/log/gitlab
      - ./.container/gitlab/data:/var/opt/gitlab
