version: '3.7'

services:
  db:
    image: dc_mysql:latest
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password --event-scheduler=ON
    environment:
      MYSQL_USER: root
      MYSQL_DATABASE: deepcode
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ${PWD:-.}/.container/mysqldata:/var/lib/mysql
    ports:
      - "3306"
  
  mongo:
    image: dc_mongo:latest
    restart: unless-stopped
    init: true
    environment:
      - MONGO_INITDB_ROOT_USERNAME=kraken
      - MONGO_INITDB_ROOT_PASSWORD=krakenloveseepcode
      - MONGO_INITDB_DATABASE=deepcode
    volumes:
      - ${PWD:-.}/.container/mongodata:/data/db
    ports:
      - "27017"

  redis:
    restart: unless-stopped
    image: dc_redis:latest
    init: true
    volumes:
      - ${PWD:-.}/.container/redisdata:/data
    ports:
      - "6379"

  suggestion:
    restart: unless-stopped
    image: dc_suggest:latest
    init: true
    environment: 
      GLOG_minloglevel: 2
    ports:
      - '5000-5002'
  
  bundle_server:
    restart: unless-stopped
    image: dc_bundle:latest
    init: true
    entrypoint: []
    command: bash ./start.sh --redis_server="redis:6379" --suggest_server="suggestion:${SUGGESTION_SERVER_PORT:-5000}" --upload_server="suggestion:${SUGGESTION_UPLOAD_PORT:-5001}" --lint_upload_server="suggestion:${SUGGESTION_LINT_PORT:-5002}" --temp_dir="./clones" --alsologtostderr --num_server_threads=8 --num_upload_threads=4 --num_lint_upload_threads=4 --health-check-enabled=false --git_disable_cert_checks="${GIT_DISABLE_CERT_CHECK:-false}"
    environment: 
      GLOG_minloglevel: 2
      GIT_DISABLE_CERT_CHECK: ${GIT_DISABLE_CERT_CHECK:-false}
    depends_on:
      - redis
      - suggestion
    ports:
      - "8001-8002"
    volumes:
      - ${PWD:-.}/.container/clones:/server/clones
    extra_hosts:
      - 'localdc:${HOST_IP:-127.0.0.1}'

  api:
    image: dc_api:latest
    environment:
      WAIT_HOSTS: db:3306, redis:6379, mongo:27017, bundle_server:8002
      PRODUCT: ${PRODUCT}
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: deepcode
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: ""
      MONGO_URL: mongodb://kraken:krakenloveseepcode@mongo:27017/deepcode?authSource=admin
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 1
      NODE_ENV: production
      BUNDLE_SERVER_URL: bundle_server:8002
      HOST_URL: ${HOST_URL}
      EXPOSED_HOST_URL: ${EXPOSED_HOST_URL:-}
      WAIT_HOSTS: db:3306, redis:6379, mongo:27017, bundle_server:8002
      LOG_GIT_HUB_RESPONSE_TIME: 0
      GIT_LAB_URL: ${GIT_LAB_URL}
      GIT_LAB_APP_ID: ${GIT_LAB_APP_ID}
      GIT_LAB_APP_SECRET: ${GIT_LAB_APP_SECRET}
      GIT_LAB_PERSONAL_ACCESS_TOKEN: ${GIT_LAB_PERSONAL_ACCESS_TOKEN:-}
      BIT_BUCKET_SERVER_URL: ${BIT_BUCKET_SERVER_URL:-}
      BIT_BUCKET_SERVER_OAUTH_CONSUMER_KEY: ${BIT_BUCKET_SERVER_OAUTH_CONSUMER_KEY:-}
      BIT_BUCKET_SERVER_USER_NAME: ${BIT_BUCKET_SERVER_USER_NAME:-}
      BIT_BUCKET_SERVER_PASSWORD: ${BIT_BUCKET_SERVER_PASSWORD:-}
      BIT_BUCKET_SERVER_OAUTH_PRIVATE_KEY: ${BIT_BUCKET_SERVER_OAUTH_PRIVATE_KEY:-}
      NODE_TLS_REJECT_UNAUTHORIZED: ${NODE_TLS_REJECT_UNAUTHORIZED:-1}
    restart: unless-stopped
    ports:
      - '3000'
    depends_on:
      - db
      - mongo
      - redis
      - bundle_server
    extra_hosts:
      - 'localdc:${HOST_IP:-127.0.0.1}'

  website:
    image: dc_website:latest
    depends_on:
      - api
    restart: unless-stopped
    environment:
      PRODUCT: ${PRODUCT}
    ports:
      - '${FRONT_PORT:-8080}:8080'
    extra_hosts:
      - 'localdc:${HOST_IP:-127.0.0.1}'
