version: '3.7'

services:
  db:
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password --event-scheduler=ON
    environment:
      MYSQL_USER: root
      MYSQL_DATABASE: deepcode
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - '3306:3306'
    volumes:
      - ${PWD:-.}/.container/mysqldata:/var/lib/mysql

  redis:
    restart: always
    image: redis:5.0.7-alpine
    ports:
      - '6379:6379'
    volumes:
      - ${PWD:-.}/.container/redisdata:/data

  suggestion:
    restart: always
    image: dc_suggest:latest
    entrypoint: []
    # --num_suggest_server_threads 2 --num_upload_server_threads 2 --num_lint_upload_server_threads 2 --num_parse_threads 2
    command: ./suggest_v5 --models ./models --parsers_dir parsing --linters_dir linters --transform python,java,javascript --alsologtostderr --eslint --pmd --pylint --tslint 
    environment: 
      GLOG_minloglevel: 2
    ports:
      - '5000:5000'
      - '5001:5001'
      - '5002:5002'
  
  bundle_server:
    restart: unless-stopped
    image: dc_bundle:latest
    entrypoint: []
    # --num_server_threads=8 --num_upload_threads=4 -- num_lint_upload_threads=4 --num_upload_threads_per_repo=4
    command: bash ./start.sh --redis_server="redis:6379" --server_port=8001 --suggest_server="suggestion:5000" --upload_server="suggestion:5001" --lint_upload_server="suggestion:5002" --temp_dir="./clones" --num_lint_upload_threads_per_repo=4 --alsologtostderr
    environment: 
      GLOG_minloglevel: 2
    depends_on:
      - redis
      - suggestion
    ports:
      - '8001:8001'
    volumes:
      - ${PWD:-.}/.container/clones:/server/clones

  api:
    image: dc_api:latest
    environment:
      PRODUCT: ${PRODUCT}
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: deepcode
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: ""
      NODE_ENV: production
      BUNDLE_SERVER_URL: http://bundle_server:8001
      HOST_URL: ${HOST_URL}
      EXPOSED_HOST_URL: ${EXPOSED_HOST_URL}
      LOG_GIT_HUB_RESPONSE_TIME: 0
      GIT_LAB_URL: ${GIT_LAB_URL}
      GIT_LAB_APP_ID: ${GIT_LAB_APP_ID}
      GIT_LAB_APP_SECRET: ${GIT_LAB_APP_SECRET}
      BIT_BUCKET_SERVER_URL: ${BIT_BUCKET_SERVER_URL}
      BIT_BUCKET_SERVER_OAUTH_CONSUMER_KEY: ${BIT_BUCKET_SERVER_OAUTH_CONSUMER_KEY}
      BIT_BUCKET_SERVER_USER_NAME: ${BIT_BUCKET_SERVER_USER_NAME}
      BIT_BUCKET_SERVER_PASSWORD: ${BIT_BUCKET_SERVER_PASSWORD}
      BIT_BUCKET_SERVER_OAUTH_PRIVATE_KEY: ${BIT_BUCKET_SERVER_OAUTH_PRIVATE_KEY}
      NODE_TLS_REJECT_UNAUTHORIZED: ${NODE_TLS_REJECT_UNAUTHORIZED:-1}
    restart: always
    command: ["yarn", "start"]
    depends_on:
      - db
      - bundle_server
    ports:
      - '3000:3000'
    extra_hosts:
      - 'localdc:${HOST_IP:-127.0.0.1}'

  website:
    image: dc_website:latest
    depends_on:
      - api
    restart: always
    environment:
      PRODUCT: ${PRODUCT}
    ports:
      - '${FRONT_PORT:-8080}:8080'
    extra_hosts:
      - 'localdc:${HOST_IP:-127.0.0.1}'
